apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-amf-config
  namespace: cemenin
  labels:
    epc-mode: amf
    app.kubernetes.io/name: open5gs
    app.kubernetes.io/component: amf
data:
  amf.yaml: |
    logger:
      path:
        file: /opt/open5gs/var/log/open5gs/amf.log

    global:
      max:
        ue: 5000  # The number of UE can be increased depending on memory size.
    #    peer: 64

    
    sbi:
      server:
        no_tls: true
        cacert: /etc/open5gs/tls/ca.crt
        key: /etc/open5gs/tls/amf.key
        cert: /etc/open5gs/tls/amf.crt
      client:
        no_tls: true
        cacert: /etc/open5gs/tls/ca.crt
        key: /etc/open5gs/tls/amf.key
        cert: /etc/open5gs/tls/amf.crt

    amf:
      sbi:
        server:
        - dev: eth0
          advertise: open5gs-amf
        client:
          nrf:
            - uri: http://open5gs-nrf:80
      ngap: 
        server:
        - dev: eth0

      guami:
        - plmn_id:
            mcc: 999
            mnc: 70
          amf_id:
            region: 2
            set: 1
      tai:
        - plmn_id:
            mcc: 999
            mnc: 70
          tac: 1

      plmn_support:
        - plmn_id:
            mcc: 999
            mnc: 70
          s_nssai:
            - sst: 1
            - sst: 1
              sd: 000001
      security:
          integrity_order : [ NIA2, NIA1, NIA0 ]
          ciphering_order : [ NEA0, NEA1, NEA2 ]
      network_name:
          full: Open5GS
      amf_name: open5gs-amf
      time:
        t3512:
          value: 540 # 9 minutes * 60 = 540 seconds

      metrics:
        server:
          - address: 0.0.0.0
            port: 9090

    nrf:
      sbi:
        - name: open5gs-nrf

    