apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-ausf-config
  namespace: nrprediger
  labels:
    epc-mode: ausf
data:
  ausf.yaml: |
    logger:
      path:
        file: /opt/open5gs/var/log/open5gs/amf.log
      
    global:
      max:
        ue: 5000  # The number of UE can be increased depending on memory size.
    #    peer: 64

    sbi:
      server:
        no_tls: true
        cacert: /etc/open5gs/tls/ca.crt
        key: /etc/open5gs/tls/ausf.key
        cert: /etc/open5gs/tls/ausf.crt
      client:
        no_tls: true
        cacert: /etc/open5gs/tls/ca.crt
        key: /etc/open5gs/tls/ausf.key
        cert: /etc/open5gs/tls/ausf.crt

    ausf:
      sbi:
        server:
            - dev: eth0
              advertise: open5gs-ausf
        client:
          nrf:
            - uri: http://open5gs-nrf:80
          
    nrf:
        sbi:
          - name: open5gs-nrf

    # scp:
    #   sbi:
    #     - name: open5gs-scp
