apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open5gs-mongodb-pv-claim
  namespace: nrprediger
spec:
  storageClassName: rook-ceph-fs-simple
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
