# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: open5gs
#   namespace: nrprediger
#   labels:
#     promotheus: open5gs-monitor
# spec:
#   selector:
#     matchLabels:
#       promotheus: open5gs-monitor
#   endpoints:
#   - interval: 30s
#     port: open5gs-amf-tcp-9090  
#   - interval: 30s
#     port: open5gs-pcf-tcp-9090
#   - interval: 30s
#     port: open5gs-smf-tcp-9090
#   - interval: 30s
#     port: open5gs-upf-tcp-9090
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-amf
  namespace: nrprediger
  labels:
    epc-mode: amf
spec:
  selector:
    matchLabels:
      epc-mode: amf
  endpoints:
  - interval: 30s
    port: open5gs-amf-tcp-9090
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-bsf
  namespace: nrprediger
  labels:
    epc-mode: bsf
spec:
  selector:
    matchLabels:
      epc-mode: bsf
  endpoints:
  - interval: 30s
    port: open5gs-bsf-tcp-9100
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-upf
  namespace: nrprediger
  labels:
    epc-mode: upf
spec:
  selector:
    matchLabels:
      epc-mode: upf
  endpoints:
  - interval: 30s
    port: open5gs-upf-tcp-9090
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-smf
  namespace: nrprediger
  labels:
    epc-mode: smf
spec:
  selector:
    matchLabels:
      epc-mode: smf
  endpoints:
  - interval: 30s
    port: open5gs-smf-tcp-9090
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-pcf
  namespace: nrprediger
  labels:
    epc-mode: pcf
spec:
  selector:
    matchLabels:
      epc-mode: pcf
  endpoints:
  - interval: 30s
    port: open5gs-pcf-tcp-9090
