apiVersion: v1
kind: Service
metadata:
  name: open5gs-udr
  namespace: nrprediger
  labels:
    epc-mode: udr
    prometheus: open5gs-monitor
spec:
  selector:
    epc-mode: udr
  ports:
    - name: http2-80
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-udr
  namespace: nrprediger
  labels:
    epc-mode: udr
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: udr
  template:
    metadata:
      labels:
        epc-mode: udr
        app: open5gs-udr
        version: 2.7.5
    spec:
      nodeSelector:
        nodetype: server
        kubernetes.io/arch: amd64
      containers:
        - name: udr
          image: gradiant/open5gs:2.7.5
          #imagePullPolicy: Always
          ports:
            - name: http2-80
              protocol: TCP
              containerPort: 80
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          volumeMounts:
            - name: open5gs-udr-config
              mountPath: /open5gs/config-map/udr.yaml
              subPath: "udr.yaml"
          command: ["open5gs-udrd", "-c", "/open5gs/config-map/udr.yaml"]
      volumes:
        - name: open5gs-udr-config
          configMap:
            name: open5gs-udr-config

