apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  namespace: nrprediger
  labels:
    epc-mode: smf
data:
  smf.yaml: |
    logger:
      path:
        file: /opt/open5gs/var/log/open5gs/smf.log

    global:
      max:
        ue: 5000  # The number of UE can be increased depending on memory size.
    #    peer: 64

    sbi:
      server:
        no_tls: true
      client:
        no_tls: true

    smf:
      sbi:
        server:
          - dev: eth0
            port: 80
            advertise: open5gs-smf
        client:
          nrf:
            - uri: http://open5gs-nrf:80
      pfcp:
        server:
          - dev: eth0
        client:
          upf:
            - address: open5gs-upf-1
      gtpc:
        server:
          - dev: eth0
      gtpu:
        server:
          - dev: eth0
      metrics:
        server:
          address: 0.0.0.0
          port: 9090
      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1
          dnn: default
      dns:
      - 10.96.0.10
      mtu: 1400
      ctf:
        enabled: auto
      freeDiameter: /etc/freeDiameter/smf.conf
      info:
        - s_nssai:
          - sst: 1
            sd: 000001
            dnn:
              - default


