apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udm-config
  namespace: nrprediger
  labels:
    epc-mode: udm
data:
  udm.yaml: |
    logger:
      path:
        file: /opt/open5gs/var/log/open5gs/udm.log
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 5000 # The number of UE can be increased depending on memory size.
    #    peer: 64
    
    sbi:
      server:
        no_tls: true
      client:
        no_tls: true

    udm:
      hnet:
        - id: 1
          scheme: 1
          key: /etc/open5gs/hnet/curve25519-1.key
        - id: 2
          scheme: 2
          key: /etc/open5gs/hnet/secp256r1-2.key
        - id: 3
          scheme: 1
          key: /etc/open5gs/hnet/curve25519-3.key
        - id: 4
          scheme: 2
          key: /etc/open5gs/hnet/secp256r1-4.key
        - id: 5
          scheme: 1
          key: /etc/open5gs/hnet/curve25519-5.key
        - id: 6
          scheme: 2
          key: /etc/open5gs/hnet/secp256r1-6.key
      sbi:
        server:
          - dev: eth0
            advertise: open5gs-udm
        client:
          nrf:
            - uri: http://open5gs-nrf:80

    nrf:
      sbi:
        - name: open5gs-nrf
          
    # scp:
    #   sbi:
    #     - name: open5gs-scp


  

