apiVersion: v1
kind: Service
metadata:
  name: open5gs-bsf
  namespace: nrprediger
  labels:
    epc-mode: bsf
    prometheus: open5gs-monitor
spec:
  selector:
    epc-mode: bsf
  ports:
    - name: http2-80
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-bsf
  namespace: nrprediger
  labels:
    epc-mode: bsf
    version: 2.6.4
    app: open5gs-bsf
spec:
  selector:
    matchLabels:
      epc-mode: bsf
  template:
    metadata:
      labels:
        epc-mode: bsf
        version: 2.7.5
        app: open5gs-bsf
    spec:
      nodeSelector:
        nodeType: server
        kubernetes.io/arch: amd64
      containers:
        - name: bsf
          image: gradiant/open5gs:2.7.5
          #imagePullPolicy: Always
          ports:
            - name: http2-80
              protocol: TCP
              containerPort: 80
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          volumeMounts:
            - name: open5gs-bsf-config
              mountPath: /open5gs/config-map/bsf.yaml
              subPath: "bsf.yaml"
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN

          command: ["open5gs-bsfd", "-c", "/open5gs/config-map/bsf.yaml"]

        # - name: metrics-bsf
        #   image: gradiant/open5gs:2.7.1
        #   command: ["/bin/prometheus-node-exporter"]
        #   volumeMounts:
        #     - name: "dev-net-tun"
        #       mountPath: "/dev/net/tun" # Needed for VPN
      volumes:
        - name: open5gs-bsf-config
          configMap:
            name: open5gs-bsf-config
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
