apiVersion: v1
kind: Service
metadata:
  name: open5gs-scp
  namespace: nrprediger
spec:
  selector:
    epc-mode: scp
  ports:
    - name: http2-80
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http2-15090
      protocol: TCP
      port: 15090
      targetPort: 15090
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-scp
  namespace: nrprediger
  labels:
    epc-mode: scp
    prometheus: open5gs-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: scp
  template:
    metadata:
      labels:
        epc-mode: scp
        app: open5gs-scp

    spec:
      nodeSelector:
        nodetype: server
        kubernetes.io/arch: arm64

      containers:
        # - name: tcpdump-scp
        #   image: gradiant/open5gs:2.7.1
        #   command: ["/bin/tcpdump", "-i", "eth0", "-s", "65535", "-G", "3600", "-w", "/var/tcpdump/scp-%F_%H%M.pcap"]
        #   volumeMounts:
        #     - name: tcpdump-persistent-storage
        #       mountPath: /var/tcpdump

        - name: scp
          image: gradiant/open5gs:2.7.5
          #imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]

          volumeMounts:
            - name: open5gs-scp-config
              mountPath: /open5gs/config-map/scp.yaml
              subPath: "scp.yaml"

            - name: "lib-modules"
              mountPath: "/lib/modules"
          command: ["open5gs-scpd", "-c", "/open5gs/config-map/scp.yaml"]

        # - name: metrics-scp
        #   image: gradiant/open5gs:2.7.1
        #   command: ["/bin/prometheus-node-exporter"]
      volumes:
        - name: open5gs-scp-config
          configMap:
            name: open5gs-scp-config

        - name: lib-modules
          hostPath:
            path: /lib/modules
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: open5gs-scp
#   namespace: nrprediger
#   labels:
#     epc-mode: scp
# spec:
#   selector:
#     matchLabels:
#       epc-mode: scp
#   endpoints:
#   - interval: 30s
#     port: http2-open5gs-scp-9100
