apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nssf-config
  namespace: nrprediger
  labels:
    epc-mode: nssf
data:
  nssf.yaml: |
    logger:
      path:
        file: /opt/open5gs/var/log/open5gs/nssf.log
    
    global:
      max:
        ue: 5000  # The number of UE can be increased depending on memory size.
    #    peer: 64

    sbi:
      server:
        no_tls: true
      client:
        no_tls: true

    nssf:
      sbi:
        server:
          - address: 0.0.0.0
            advertise: open5gs-nssf
        client:
          nrf:
            - uri: http://open5gs-nrf:80
          nsi:
            - uri: http://open5gs-nrf:80
              s_nssai:
                sst: 1
            - uri: http://open5gs-nrf:80
              s_nssai:
                sst: 1
                sd: 1
            - uri: http://open5gs-nrf:80
              s_nssai:
                sst: 2
                sd: 2
            - uri: http://open5gs-nrf:80
              s_nssai:
                sst: 3
                sd: 3
            - uri: http://open5gs-nrf:80
              s_nssai:
                sst: 4
                sd: 4
