apiVersion: v1
kind: Service
metadata:
  name: open5gs-nssf
  namespace: nrprediger
  labels:
    epc-mode: nssf
    prometheus: open5gs-monitor
spec:
  selector:
    epc-mode: nssf
  ports:
    - name: http2-80
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-nssf
  namespace: nrprediger
  labels:
    epc-mode: nssf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: nssf
  template:
    metadata:
      labels:
        epc-mode: nssf
        app: open5gs-nssf
        version: 2.7.5
    spec:
      nodeSelector:
        nodetype: server
        kubernetes.io/arch: amd64
      containers:
        - name: nssf
          image: gradiant/open5gs:2.7.5
          #imagePullPolicy: Always
          ports:
            - name: http2-80
              protocol: TCP
              containerPort: 80
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          volumeMounts:
            - name: open5gs-nssf-config
              mountPath: /open5gs/config-map/nssf.yaml
              subPath: "nssf.yaml"
          command: ["open5gs-nssfd", "-c", "/open5gs/config-map/nssf.yaml"]
      volumes:
        - name: open5gs-nssf-config
          configMap:
            name: open5gs-nssf-config

