apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-pcf-config
  namespace: nrprediger
  labels:
    epc-mode: pcf
data:
  pcf.yaml: |
    db_uri: mongodb://mongo/open5gs
    
    logger:
      path:
        file: /opt/open5gs/var/log/open5gs/pcf.log

    global:
      max:
        ue: 5000  # The number of UE can be increased depending on memory size.
    #    peer: 64

    sbi:
      server:
        no_tls: true
      client:
        no_tls: true

    pcf:
      sbi:
        server:
          - address: 0.0.0.0
            advertise: open5gs-pcf
        client:
          nrf:
            - uri: http://open5gs-nrf:80
      metrics:
        server:
          - address: 0.0.0.0
            port: 9090
    nrf:
      sbi:
        - name: open5gs-nrf
