apiVersion: v1
kind: Service
metadata:
  name: open5gs-pcf
  namespace: nrprediger
  labels:
    epc-mode: pcf
    prometheus: open5gs-monitor
spec:
  selector:
    epc-mode: pcf
  ports:
    - name: http2-80
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-pcf
  namespace: nrprediger
  labels:
    epc-mode: pcf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: pcf
  template:
    metadata:
      labels:
        epc-mode: pcf
        app: open5gs-pcf
        prometheus: open5gs-monitor
        version: 2.7.5
    spec:
      nodeSelector:
        nodetype: server
        kubernetes.io/arch: amd64
      containers:
        - name: pcf
          image: gradiant/open5gs:2.7.5
          #imagePullPolicy: Always
          ports:
            - name: http2-80
              protocol: TCP
              containerPort: 80
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          volumeMounts:
            - name: open5gs-pcf-config
              mountPath: /open5gs/config-map/pcf.yaml
              subPath: "pcf.yaml"
          command: ["open5gs-pcfd", "-c", "/open5gs/config-map/pcf.yaml"]
      volumes:
        - name: open5gs-pcf-config
          configMap:
            name: open5gs-pcf-config
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-pcf
  namespace: nrprediger
  labels:
    epc-mode: pcf
spec:
  selector:
    matchLabels:
      epc-mode: pcf
  endpoints:
    - interval: 5s
      port: http2-open5gs-pcf-9090
