apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-nrf-config
  namespace: nrprediger
  labels:
    epc-mode: nrf
data:
  nrf.yaml: |
    logger:
      path:
        file: /opt/open5gs/var/log/open5gs/nrf.log

    global:
      max:
        ue: 5000  # The number of UE can be increased depending on memory size.
    #    peer: 64

    sbi:
      server:
        no_tls: true
        cacert: /etc/open5gs/tls/ca.crt
        key: /etc/open5gs/tls/nrf.key
        cert: /etc/open5gs/tls/nrf.crt
      client:
        no_tls: true
        cacert: /etc/open5gs/tls/ca.crt
        key: /etc/open5gs/tls/nrf.key
        cert: /etc/open5gs/tls/nrf.crt

    nrf:
      serving: # 5G roaming requires PLMN in NRF
      - plmn_id:
          mcc: 999
          mnc: 70
      sbi:
        server:
        - address: 0.0.0.0
          advertise: open5gs-nrf

    # scp:
    #   sbi:
    #     - name: open5gs-scp

    parameter:
    max:
    time:

