apiVersion: v1
kind: Service
metadata:
  name: open5gs-webui
  namespace: nrprediger
  labels:
    epc-mode: webui
spec:
  selector:
    epc-mode: webui
  ports:
    - name: http2-80
      protocol: TCP
      port: 80
      targetPort: 9999
    - name: http2-9999
      protocol: TCP
      port: 9999
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-webui
  namespace: nrprediger
  labels:
    epc-mode: webui
    app: webui
    version: v2.4.11
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: webui
      
  template:
    metadata:
      labels:
        epc-mode: webui
        app: webui
        version: v2.4.11
    spec:  
      nodeSelector:
        kubernetes.io/arch: amd64
        nodetype: server

      containers:
        - name: webui
          image: gradiant/open5gs-webui:2.7.5
          ports:
            - name: http2-80
              protocol: TCP
              containerPort: 80
            - name: http2-9999
              protocol: TCP
              containerPort: 9999  
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          volumeMounts:
            - name: "dev-net-tun"
              mountPath: "/dev/net/tun" # Needed for VPN
          env:
            - name: DB_URI 
              value: mongodb://mongo/open5gs
            - name: HOSTNAME
              value: 0.0.0.0
          securityContext:
            runAsUser: 0
          command: ["npm", "run", "dev"]
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun

